version: '3.8'
services:
  loadgen:
    image: nardis555/ikon-loadgen:latest
    volumes:
      - .env.ACCOUNTS:/usr/src/app/.env.ACCOUNTS
      - .env.ORDERS:/usr/src/app/.env.ORDERS
      - .env:/usr/src/app/.env